---
- hosts: web
  remote_user: "{{ ansible_user }}"
  gather_facts: no
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Wait 300 seconds, but only start checking after 20 seconds
      wait_for_connection:
        delay: 20
        timeout: 300
    - name: ensure tomcat is at the latest version
      apt:
        name: tomcat
        state: latest
      become: yes
    - name: start tomcat
      service:
        name: tomcat
        state: started
      become: yes
